spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 2004
  mvc:
    throw-exception-if-no-handler-found: true



server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true